# Generated by Django 3.2.9 on 2021-11-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0002_auto_20211107_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='instance_name',
            field=models.TextField(default='puppy-server'),
            preserve_default=False,
        ),
    ]
