# Generated by Django 3.2.9 on 2021-11-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0004_alter_instance_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='type',
            field=models.TextField(default='E1 Kalahari'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='ip',
            field=models.TextField(default='Setting Up'),
        ),
    ]
